// M1/VueJS/jour4/src/components/Menu.vue
<script setup lang="ts">
</script>

<template>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container">
            <a class="navbar-brand" href="/">Jour 4</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a  class="nav-link "  href="/">Accueil</a>
                    </li>
                    <li class="nav-item" >
                        <a class="nav-link"  href="/">Contact</a>
                    </li>

                    <li  class="nav-item">
                        <a class="nav-link"  href="/">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"  href="/">Login</a>
                    </li>
                    <li class="nav-item" >
                        <a class="nav-link"  href="/">Créer un compte</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>

// M1/React/jour2/src/components/Menu.jsx
import { Link } from "react-router-dom";

const Menu = () => {
	return (
		<nav className="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
			<div className="container">
				<Link to="/" className="navbar-brand">
					Logo
				</Link>
				<button className="navbar-toggler" type="button">
					<span className="navbar-toggler-icon"></span>
				</button>
				<div className="collapse navbar-collapse" id="navbarSupportedContent">
					<ul className="navbar-nav ms-auto mb-2 mb-lg-0">
						<li className="nav-item">
							<Link to="/" className="nav-link active">
								Home
							</Link>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	);
};

export default Menu;
