// M1/Typescript/rick_and_morty_api/src/components/Navbar.tsx
import { ReactComponent as Logo } from "../assets/logo.svg";

const Navbar = () => {
	return (
		<nav className="navbar navbar-expand-lg bg-body-tertiary">
			<div className="container">
				<a className="navbar-brand" href="#">
					<Logo />
				</a>

				<div className="collapse navbar-collapse my-nav" id="navbarSupportedContent">
					<ul className="my-navbar-nav ms-auto mb-2 mb-lg-0">
						<li className="nav-item">
							<a className="my-nav-link" aria-current="page" href="https://rickandmortyapi.com/documentation">
								Docs
							</a>
						</li>
						<li className="nav-item">
							<a className="my-nav-link my-secondary-btn" href="https://rickandmortyapi.com/support-us">
								Support them
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	);
};

export default Navbar;

// M1/VueJS/e-commerce/src/components/Navbar.vue
<script setup lang="ts">

</script>

<template>
    <div>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
            <div class="container">
                <a class="navbar-brand" href="#">E-commerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</template>

<style lang="scss" scoped>

</style>
